- hosts: all
  become: true
  gather_facts: false
  vars:
    shell: /bin/bash
    number_of_cpu_cores: 2
    node_version: 21
  roles:
    - role: initial
    - role: docker
    - role: node
    - role: nginx